### ISSUE TITLE
[feat]: Implement the deck progress tracker

### ISSUE THREAD

**Issue by ghpranav** [ghpranav/VocabGenie#2]
### Summary

Currently, the home page has a dummy progress tracker for each deck. Implement a fully functional progress tracker that tracks the progress of each deck.

### Basic Example

The implementation should ensure
- [ ] The progress is stored in the user's Local Storage
- [ ] Should track only the mastered words in each deck
- [ ] Should show the overall progress for each deck on the home page

**Comment by prithvi206** [comment]
@ghpranav can you Assign this issue to me.

**Comment by prithvi206** [comment]
@ghpranav I have fixed deployment issue , can you check the pr now.
